const tamplatesType = {
  SET_TAMPLATES: "SET_TAMPLATES",
  ADD_NEW_TAMPLATE: "ADD_NEW_TAMPLATE",
  UPDATE_TAMPLATE: "UPDATE_TAMPLATE",
  DELETE_TAMPLATE: "DELETE_TAMPLATE",
};

export default tamplatesType;
